language: go
go:
  - 1.9

# we use dep...
env:
  - DEP_VERSION="0.4.1"

before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

# we don't want to test the 'js' directory at the moment
# (gopherjs can't be vendored by dep, and, well, doesn't make much sense anyway)
script:
  - go test -v .
